name: package-manager-ci
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
jobs:
  pnpm:
    name: pnpm package manager on ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: ^6.0.0
      - name: Install dependancies
        run: pnpm install
      - name: Tests
        shell: bash
        run: pnpm run test:ci
